name: 🚀 Extreme Cool Commit Pattern (Dark Blocks)

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Ensure Commit File Exists
        run: |
          echo "GitHub Auto Commit History" > commit_history.txt
          git add commit_history.txt

      - name: ⏳ Modify & Commit (Extreme Pattern)
        run: |
          for DAY in {300..1..2}  # 🗓 Skipping every alternate day
          do
            # 🎲 Random probability-based blocks
            PROBABILITY=$(( RANDOM % 100 ))

            if (( PROBABILITY < 10 )); then
              COMMITS_PER_DAY=$(( RANDOM % 3 + 1 ))  # 🔵 10% chance of 1-3 commits (light green)
            elif (( PROBABILITY < 40 )); then
              COMMITS_PER_DAY=$(( RANDOM % 6 + 4 ))  # 🟢 30% chance of 4-10 commits (medium green)
            elif (( PROBABILITY < 70 )); then
              COMMITS_PER_DAY=$(( RANDOM % 10 + 10 ))  # 🔥 30% chance of 10-20 commits (dark green)
            else
              COMMITS_PER_DAY=$(( RANDOM % 15 + 20 ))  # 🚀 30% chance of 20-35 commits (very dark green)
            fi

            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              echo "Cool Edit #$i on $(date -d "$DAY days ago" +%Y-%m-%d)" >> commit_history.txt
              git add commit_history.txt
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🚀 Cool Dark Block - $(date -d "$DAY days ago")"
            done
          done

      - name: 🚀 Push Changes
        run: git push
        
