name: 🚀 "Hi" Contribution Graph  

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  create_hi_pattern:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Create Commit Folder (if not exists)
        run: |
          [ -d autocommits ] || mkdir autocommits

      - name: 📝 Generate "Hi" Pattern Commits
        run: |
          # 🎨 Define the "Hi" pattern (using specific days)
          HI_DAYS=(10 11 12 13 14 15 16 17 18  # "H" vertical left
                   22  # "H" middle bar
                   30 31 32 33 34 35 36 37 38  # "H" vertical right
                   50 51 52 53 54 55 56 57 58  # "I" vertical
          )

          for DAY in "${HI_DAYS[@]}"
          do
            COMMITS_PER_DAY=$(( RANDOM % 8 + 5 ))  # Random commit count (5-12)
            
            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              FILE_NAME="autocommits/commit_$(date -d "2025-01-01 +$DAY days" +%Y%m%d)_$(( RANDOM % 100 )).txt"
              echo "🔥 Hi Commit at $(date -d "2025-01-01 +$DAY days") - Random: $RANDOM" > $FILE_NAME
              git add $FILE_NAME
              
              GIT_COMMITTER_DATE="$(date -d "2025-01-01 +$DAY days" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "2025-01-01 +$DAY days" --rfc-2822)" \
              git commit -m "🔥 Hi Commit - $(date -d "2025-01-01 +$DAY days")" --date "$(date -d "2025-01-01 +$DAY days")"
            done
          done
          
          git push
          
