name: "🔥 Multi-Diagonal Gradient Pattern 🔥"

on:
  workflow_dispatch: # Manually Trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: "📥 Checkout Repository"
        uses: actions/checkout@v3

      - name: "⚙️ Set Git User"
        run: |
          git config --global user.name "DiagonalGradientBot"
          git config --global user.email "diagonal@gradient.com"

      - name: "🔥 Generate Multi-Diagonal Gradient Pattern 🔥"
        run: |
          start_date="2024-08-01"
          end_date=$(date +"%Y-%m-%d")

          current_date="$start_date"
          gap=0 # Yeh gap diagonal shift ke liye

          while [ "$current_date" != "$end_date" ]; do
            if (( gap % 7 == 0 )); then  # 7 days ke gap pe diagonal commit karega
              for j in {0..3}; do  # Multiple diagonal lines create karega
                commit_date=$(date -I -d "$current_date + $j days")
                
                for i in {1..15}; do  # 15 Commits per day for Main Dark Line
                  echo "🔥 Dark Line Commit $i on $commit_date" >> commitfile.txt
                  git add commitfile.txt
                  GIT_COMMITTER_DATE="$commit_date 12:00:00" GIT_AUTHOR_DATE="$commit_date 12:00:00" git commit -m "🔥 Dark Line Commit on $commit_date"
                done

                for side_offset in {-1,1}; do  # Side Boxes Medium Dark
                  side_commit_date=$(date -I -d "$commit_date + $side_offset days")
                  for i in {1..7}; do  # 7 Commits per day for Side Boxes
                    echo "⚡ Side Box Commit $i on $side_commit_date" >> commitfile.txt
                    git add commitfile.txt
                    GIT_COMMITTER_DATE="$side_commit_date 12:00:00" GIT_AUTHOR_DATE="$side_commit_date 12:00:00" git commit -m "⚡ Side Box Commit on $side_commit_date"
                  done
                done
              done
            fi
            gap=$((gap+1))
            current_date=$(date -I -d "$current_date + 1 day")
          done

          git push
          
