
name: 🚀 Zig-Zag Backfill (Last 5 Months - Alternate Days Skipped)  

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Create Commit Folder (if not exists)
        run: |
          [ -d auto_commits ] || mkdir auto_commits

      - name: ⏳ Backfill Commits for 5 Months (Zig-Zag + Alternate Days Skipped)
        run: |
          for DAY in {150..1..2}  # 🔥 Skip Every Alternate Day (..2)
          do
            # 🔀 Zig-Zag Logic: Odd Days (Dark), Even Days (Light)
            if (( DAY % 4 == 0 )); then
              COMMITS_PER_DAY=$(( RANDOM % 4 + 1 ))  # Light Green: 1-4 commits
            else
              COMMITS_PER_DAY=$(( RANDOM % 7 + 4 ))  # Dark Green: 4-10 commits
            fi

            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              FILE_NAME="auto_commits/commit_$(date -d "$DAY days ago" +%Y%m%d)_$(( RANDOM % 100 )).txt"
              echo "🚀 Auto Commit at $(date -d "$DAY days ago") - Random: $RANDOM" > $FILE_NAME
              git add $FILE_NAME
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🟢 Zig-Zag Commit - $(date -d "$DAY days ago")" --date "$(date -d "$DAY days ago")"
            done
          done
          
          git push
          
