name: 🚀 Random Pattern Backfill (Last 10 Months - Alternate Days)  

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Create Commit Folder (if not exists)
        run: |
          [ -d autocommits ] || mkdir autocommits

      - name: ⏳ Backfill Commits for 10 Months (Random Pattern, Alternate Days)
        run: |
          for DAY in {365..1..2}  # 🗓 Skipping every alternate day
          do
            # 🎲 Random probability-based pattern
            PROBABILITY=$(( RANDOM % 100 ))
            
            if (( PROBABILITY < 20 )); then
              COMMITS_PER_DAY=$(( RANDOM % 2 + 1 ))  # 🔵 20% chance of 1-2 commits (very light green)
            elif (( PROBABILITY < 50 )); then
              COMMITS_PER_DAY=$(( RANDOM % 4 + 2 ))  # 🟢 30% chance of 2-6 commits (light green)
            elif (( PROBABILITY < 80 )); then
              COMMITS_PER_DAY=$(( RANDOM % 7 + 5 ))  # 🔥 60% chance of 5-12 commits (medium green)
            else
              COMMITS_PER_DAY=$(( RANDOM % 10 + 10 ))  # 🚀 80% chance of 10-20 commits (dark green)
            fi

            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              FILE_NAME="autocommits/commit_$(date -d "$DAY days ago" +%Y%m%d)_$(( RANDOM % 100 )).txt"
              echo "🚀 Auto Commit at $(date -d "$DAY days ago") - Random: $RANDOM" > $FILE_NAME
              git add $FILE_NAME
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🟢 Random Commit - $(date -d "$DAY days ago")" --date "$(date -d "$DAY days ago")"
            done
          done
          
          git push
          
