name: 🚀 Xtreme Dark Stylish GitHub Contributions

on:
  workflow_dispatch:  # 🔄 Manually Run karne ke liye

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Ensure Commit File Exists
        run: |
          echo "🔥 Coolest Contribution Log" > commit_history.txt
          git add commit_history.txt

      - name: ⏳ Modify & Commit (Extreme Dark + Stylish)
        run: |
          for DAY in {365..1..-1}  # 🔄 1 Saal ka loop
          do
            # 🔥 80% chance commit karega, sirf 20% gap hoga
            SKIP_DAY=$(( RANDOM % 100 ))
            if (( SKIP_DAY < 20 )); then
              echo "Skipping $(date -d "$DAY days ago" +%Y-%m-%d) ❌"
              continue
            fi

            # 🎲 Cool Stylish Commit Pattern
            STYLE=$(( RANDOM % 5 ))

            case $STYLE in
              0) COMMITS_PER_DAY=$(( RANDOM % 50 + 50 )) ;;  # 🔥 FULL DARK BLOCKS (50-100 commits)
              1) COMMITS_PER_DAY=$(( RANDOM % 20 + 30 )) ;;  # 🟢 MEDIUM DARK (30-50 commits)
              2) COMMITS_PER_DAY=$(( RANDOM % 5 + 1 )) ;;    # 🟢 LIGHT SHADE (1-5 commits)
              3) COMMITS_PER_DAY=$(( RANDOM % 80 + 20 )) ;;  # 💀 MAX DARK (20-100 commits)
              4) COMMITS_PER_DAY=$(( RANDOM % 40 + 10 )) ;;  # 🔄 GLITCH PATTERN (10-50 commits)
            esac

            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              echo "🔥 Stylish Commit #$i on $(date -d "$DAY days ago" +%Y-%m-%d)" >> commit_history.txt
              git add commit_history.txt
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🔥 Stylish Xtreme Commit - $(date -d "$DAY days ago")"
            done
          done

      - name: 🚀 Push Changes
        run: git push
        
