name: 🚀 Instant Backfill Commits  

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Create Commit Folder (if not exists)
        run: |
          [ -d auto_commits ] || mkdir auto_commits

      - name: ⏳ Backfill Commits for 1 Month (Fixed Version)
        run: |
          for DAY in {30..1}
          do
            COMMITS_PER_DAY=$(( RANDOM % 8 + 3 ))  # 🌟 3-10 commits per day
            
            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              FILE_NAME="auto_commits/commit_$(date -d "$DAY days ago" +%Y%m%d)_$(( RANDOM % 100 )).txt"
              echo "🚀 Auto Commit at $(date -d "$DAY days ago") - Random: $RANDOM" > $FILE_NAME
              git add $FILE_NAME
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🟢 Fast Commit - $(date -d "$DAY days ago")" --date "$(date -d "$DAY days ago")"
            done
          done
          
          git push
          
