name: Auto Commit

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 1 minute (for testing)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: Fake Commit
        run: |
          echo "Fake Contribution $(date) - Random: $RANDOM" >> commit_ttg.txt
          git add commit_ttg.txt
          git commit -m "Automated Commit - $(date)"
          git push
          
