name: 🚀 Ultra Cool GitHub Contributions

on:
  workflow_dispatch:  # 🔄 Manually Trigger

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠 Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: 📂 Ensure Commit File Exists
        run: |
          echo "Commit History Log" > commit_history.txt
          git add commit_history.txt

      - name: ⏳ Modify & Commit (Cool Random Gaps)
        run: |
          for DAY in {300..1..1}  # 🗓 300 days loop
          do
            # 🎲 Decide whether to SKIP this day
            SKIP_DAY=$(( RANDOM % 100 ))

            if (( SKIP_DAY < 25 )); then
              echo "Skipping $(date -d "$DAY days ago" +%Y-%m-%d) ❌"
              continue  # 🛑 Skip 25% days randomly
            fi

            # 🎲 Randomized Commit Density
            PROBABILITY=$(( RANDOM % 100 ))

            if (( PROBABILITY < 10 )); then
              COMMITS_PER_DAY=$(( RANDOM % 5 + 1 ))  # 🍀 10% chance of 1-5 commits
            elif (( PROBABILITY < 30 )); then
              COMMITS_PER_DAY=$(( RANDOM % 10 + 6 ))  # 🌿 20% chance of 6-15 commits
            elif (( PROBABILITY < 60 )); then
              COMMITS_PER_DAY=$(( RANDOM % 20 + 16 ))  # 🟢 30% chance of 16-35 commits
            elif (( PROBABILITY < 85 )); then
              COMMITS_PER_DAY=$(( RANDOM % 30 + 36 ))  # 🔥 25% chance of 36-65 commits
            else
              COMMITS_PER_DAY=$(( RANDOM % 40 + 66 ))  # 🚀 15% chance of 66-105 commits (Extreme Dark)
            fi

            for i in $(seq 1 $COMMITS_PER_DAY)
            do
              echo "Cool Commit #$i on $(date -d "$DAY days ago" +%Y-%m-%d)" >> commit_history.txt
              git add commit_history.txt
              
              GIT_COMMITTER_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              GIT_AUTHOR_DATE="$(date -d "$DAY days ago" --rfc-2822)" \
              git commit -m "🔥 Ultra Cool Block - $(date -d "$DAY days ago")"
            done
          done

      - name: 🚀 Push Changes
        run: git push
        
