name: Auto Commit Every 10 Minutes

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Manual trigger option

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "otterai"
          git config --global user.email "uncle@flash.co"

      - name: Make a Fake Commit
        run: |
          echo "Fake Contribution $(date)" > fake_commit.txt
          git add fake_commit.txt
          git commit -m "Added a fake contribution"
          git push
          
